### ISSUE TITLE
Update wilayate

### ISSUE THREAD

**Issue by aminalgeria** [othmanus/algeria-cities#11]
Time to update the provinces :-) 
 

> تقرر خلال إجتماع مجلس الوزراء اليوم الثلاثاء ترقية 10 ولايات منتدبة بالجنوب الكبير إلى ولايات جديدة و يتعلق الأمر بكل من ولايات: برج باجي مختار ، جانت ، عين صالح ، المنيعة ، عين قزام ،المغير ، تقرت ، بني عباس، تيميمون، اولاد جلال.

الصفحة 13 إلى 16 من الجريدة الرسمية
https://www.joradp.dz/FTP/jo-arabe/2019/A2019078.pdf

**Comment by sneetsher** [comment]
It is better to keep them separate in the list. Because it will take time to be effective on the ground. 

I mean it will take more than 1 year to change administrative structure and documents (public  buildings, ID's, Vehicle plates, Road signing, Addresses,..)

**Comment by othmanus** [comment]
Thanks @aminalgeria for the suggestion.

I updated the list of wilayas and dairas and noticed that the new "wilayates" are actually listed as dairas, more precisely like: `ولايات منتدبة`

In any case, they are included in v2.0, feel free to have a look.
