### ISSUE TITLE
Non Correspondance (nom commune <-> wilaya)

### ISSUE THREAD

**Issue by selmo47** [othmanus/algeria-cities#2]
On sait bien que chaque nom de wilaya est un nom de comune (Sauf Alger et Alger Centre)
Alors la requetes 

doit retourner Alger seulement  
Mais quand on l'exécute comme ça, elle retoune aussi M'sila et Tamanrasset
car 
- La wilaya est écrite "Tamanrasset" et la commune "Tamanghasset"
- La wilaya est écrite "M'sila" et la commune "Msila"

C'est deux (02) cas doit être unifiés (selon la nomonclature officielle)

**Comment by touhami92** [comment]
oui tu a entièrement raison, 
crée une pull request

**Comment by hriad** [comment]
Un petit merge please!

**Comment by othmanus** [comment]
Merci pour la contribution.

Ces noms sont fixés selon la source officielle dans la version 2.0.
