### ISSUE TITLE
La liste des codes postaux

### ISSUE THREAD

**Issue by ghost** [othmanus/algeria-cities#3]
Bonjour,
La liste des codes postaux des localités sont incorrects.

**Comment by Zdakman** [comment]
ou est l'erreur svp

**Comment by sarraRoza** [comment]
Oui, moi aussi j'ai remarqué qu'il y'a une erreur

**Comment by foxmedo** [comment]
elle est ou l'erreur exactement SVP ?

**Comment by sarraRoza** [comment]
un petit example la commune Ammi Moussa à Relizane, son code postal est 48004 et pas celui qui est affiché !

**Comment by foxmedo** [comment]
dans ce cas la pouvons nous travailler sur un projet ou un fork de celui la je vois que le propriétaire du projet ne s'intéresse plus ?

**Comment by sarraRoza** [comment]
foxmedo, je pense que le problème est dans le fait de mapper une commune avec un seul code postal ! Ce qui est faux. Un code postale correspond à une poste et pas une commune et comme la commune peut avoir plusieurs bureaux de postes, chacun avec un code différent .. cela pose des problèmes.

**Comment by foxmedo** [comment]
mais ya un code par default pour chaque commune je pense, je vais confirmer avec AlgeriePoste et je reviens vers vous

**Comment by othmanus** [comment]
Bonjour,

Effectivement, le code commune dans ces données est le code ONS et non pas le code postal, je m'excuse pour la confusion. Pour l'instant, ces données ne disposent pas encore le code postal.
