### ISSUE TITLE
Traduction en Arabe

### ISSUE THREAD

**Issue by hiddeneyes02** [othmanus/algeria-cities#5]
Merci pour ces informations très utiles et pratiques. Mais en tant qu'arabe ne devrait-il pas avoir les noms en arabe? Je sais que c'est beaucoup de travail; mais comme c'est déjà fait en latin, l'arabe devrait être faisable aussi

**Comment by mohsenuss91** [comment]
@hiddeneyes02  Check out this project: [Algerian Administrative Division](https://github.com/mohsenuss91/AlgerianAdministrativeDivision)

**Comment by othmanus** [comment]
Bonjour @hiddeneyes02 

D'abord, mes excuses pour la réponse très tardive.

Je viens de mettre à jour les données en incluant les noms en Arabe.

**Comment by mohsenuss91** [comment]
> Bonjour @hiddeneyes02
> 
> D'abord, mes excuses pour la réponse très tardive.
> 
> Je viens de mettre à jour les données en incluant les noms en Arabe.

Merci pour votre aide @othmanus 
👏
