### ISSUE TITLE
Code postaux incorrects

### ISSUE THREAD

**Issue by AbdelhamidLarachi** [othmanus/algeria-cities#8]
bonjour, 
merci pour les effors frère, mais presque toutes les codes sont incorrects meme au niveau de wilaya d'alger :/ en effet je trouve que tu as pris les codes ONS et non pas postal.

**Comment by khialb32** [comment]
oui c vrais

**Comment by othmanus** [comment]
Bonjour Abdelhamid,

D'abord, mes excuses pour la réponse tardive.

Le code commune dans ces fichiers ne représentent pas les codes postaux, comme tu l'as bien mentionné.
Une commune peut avoir plusieurs codes postaux, mais pour l'instant ils ne sont pas compris dans les données.
